### ISSUE TITLE
question about the ablation studies

### ISSUE THREAD

**Issue by Ko8e-24** [alibaba/cluster-contrast-reid#1]
Hi, I just read the "Cluster Contrast" paper on arxiv and found it a creative work. However, I am still confused on the ablation studies of Table 4, how do you fix the cluster size to a constant number since it can not be pre-defined in DBSCAN clustering method?

**Comment by daizuozhuo** [comment]
We sample a constant number of images from DBSCAN clustering result.

**Comment by Ko8e-24** [comment]
I see, thank you!
