### ISSUE TITLE
Sorry that we didn't not provides the CM_hard command in readme.md. I will update it.

### ISSUE THREAD

**Issue by jinx-USTC** [alibaba/cluster-contrast-reid#11]
Sorry that we didn't not provides the CM_hard command in readme.md. I will update it.
For this command:
CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/cluster_contrast_train_usl.py -b 256 -a resnet_ibn50a -d market1501 --iters 400 --momentum 0.1 --eps 0.4 --num-instances 16 --pooling-type gem --use-hard --logs-dir /data0/developer/cluster-contrast/examples/logs/gem-hard
You will get result:
Mean AP: 87.0%
CMC Scores:
  top-1          94.6%
  top-5          98.2%
  top-10         98.8%
which is much higher than paper result since we use gem pooling.

If use average pooling like:
CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/cluster_contrast_train_usl.py -b 256 -a resnet_ibn50a -d market1501 --iters 400 --momentum 0.1 --eps 0.4 --num-instances 16 --pooling-type avg --use-hard
You will get result similar or a litter higher than our paper:
Mean AP: 84.5%
CMC Scores:
  top-1          93.6%
  top-5          97.5%
  top-10         98.4%

Thank!

_Originally posted by @daizuozhuo in https://github.com/alibaba/cluster-contrast-reid/issues/2#issuecomment-828402955_

**Comment by jinx-USTC** [comment]
Hi, could CM_hard benefits the framework when backbone is resnet50, not resnet_ibn50a ?  How finetune/adjust some specific hyper-parameters?

**Comment by wangguangyuan** [comment]
Hello, I have updated the code, please update the code to the latest
