### ISSUE TITLE
i see in the experiment you only train in batch 256,different from that in method like spcl,and is the good result get by larger batchsize?

### ISSUE THREAD

**Issue by linwang123456** [alibaba/cluster-contrast-reid#12]

**Comment by linwang123456** [comment]
in spcl,the batch size is only 64

**Comment by wangguangyuan** [comment]
The results of batch size 64 on all
four person reID datasets are shown in Table 2. It shows
our method consistently performs better than SPCL, which
is the SOTA USL method. By the way, it is acknowledged
by the author(https://github.com/yxgeee/SpCL/issues/6#issuecomment-662795770 https://github.com/yxgeee/SpCL/issues/9#issuecomment-669001144)
that the optimal batch size for SPCL is 64
while our method can be benefit by large batch size.
![image](https://user-images.githubusercontent.com/5125004/124212214-266ccb80-db21-11eb-883a-676582d0db6e.png)

**Comment by linwang123456** [comment]
thanks,this is more convictive for me,is there an experiment on veri776 with batchsize 64? and i have a question why the unconsistency update of feature in cluster can harm the perfomence,is it the result of experiment,or some theory get by math,or only something you think will&nbsp; work.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月2日(星期五) 上午10:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/cluster-contrast-reid] i see in the experiment you only train in batch 256,different from that in method like spcl,and is the good result get by larger batchsize? (#12)





 
The results of batch size 64 on all
 four person reID datasets are shown in Table 2. It shows
 our method consistently performs better than SPCL, which
 is the SOTA USL method. By the way, it is acknowledged
 by the author(yxgeee/SpCL#6 (comment) yxgeee/SpCL#9 (comment))
 that the optimal batch size for SPCL is 64
 while our method can be benefit by large batch size.

**Comment by wangguangyuan** [comment]
抱歉，我们没有做veri776 batchsize 64的实验，这个你可以通过我们发布的代码很容易验证。

集群中特征的不一致更新会损害性能，首先实验结果已经验证了这一点，同时如果你理解之前方法在求cluster center的过程，很容易能够发现这些方法的问题。简单做一下解释，之前方法memory dictionary 是instance level的，每个迭代取min-batch = k x p数量的数据训练及更新memory dictionary，k 是min-batch 中的类别数，p是每个类别实例数，即每次每个类别按相同数量的实例数更新memory dictionary，但是训练数据集中每一类别包含的实例数量不同，就会导致不同类别更新完其实例数据需要的迭代次数不一致，可以看成不同类别间存在更新不一致问题。同时之前方法在每个迭代计算cluster center 是采用对同一类别的所有实例特征求均值，由于之前方法每次迭代只能更新p个数据，所以也导致同一类别包含了不同迭代次数下的模型提取的实例特征，导致同一类的实例特征也存在更新不一致问题。

**Comment by linwang123456** [comment]
我主要是好奇 更新速度不一样会损害网络的性能这一想法有没有理论上的依据 或者更直观的想法 原来的方法会造成更新速度不一致这一点我是理解的 只是不太理解为什么不一致就会造成性能的下降&nbsp;这一观点是从 contrastive learning带来的吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月2日(星期五) 中午11:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/cluster-contrast-reid] i see in the experiment you only train in batch 256,different from that in method like spcl,and is the good result get by larger batchsize? (#12)





 
抱歉，我们没有做veri776 batchsize 64的实验，这个你可以通过我们发布的代码很容易验证。
 
集群中特征的不一致更新会损害性能，首先实验结果已经验证了这一点，同时如果你理解之前方法在求cluster center的过程，很容易能够发现这些方法的问题。简单做一下解释，之前方法memory dictionary 是instance level的，每个迭代取min-batch = k x p数量的数据训练及更新memory dictionary，k 是min-batch 中的类别数，p是每个类别实例数，即每次每个类别按相同数量的实例数更新memory dictionary，但是训练数据集中每一类别包含的实例数量不同，就会导致不同类别更新完其实例数据需要的迭代次数不一致，可以看成不同类别间存在更新不一致问题。同时之前方法在每个迭代计算cluster center 是采用对同一类别的所有实例特征求均值，由于之前方法每次迭代只能更新p个数据，所以也导致同一类别包含了不同迭代次数下的模型提取的实例特征，导致同一类的实例特征也存在更新不一致问题。

**Comment by wangguangyuan** [comment]
有些论文介绍了一致性的原理可以参考一下 https://arxiv.org/pdf/2010.03622.pdf  https://arxiv.org/pdf/1904.12848.pdf

简单说一下我的理解，速度不一致最终导致提取的同一个图片的特征表示不同，会影响后续的模型优化。

**Comment by lastonephy** [comment]
> The results of batch size 64 on all
> four person reID datasets are shown in Table 2. It shows
> our method consistently performs better than SPCL, which
> is the SOTA USL method. By the way, it is acknowledged
> by the author([yxgeee/SpCL#6 (comment)](https://github.com/yxgeee/SpCL/issues/6#issuecomment-662795770) [yxgeee/SpCL#9 (comment)](https://github.com/yxgeee/SpCL/issues/9#issuecomment-669001144))
> that the optimal batch size for SPCL is 64
> while our method can be benefit by large batch size.
> ![image](https://user-images.githubusercontent.com/5125004/124212214-266ccb80-db21-11eb-883a-676582d0db6e.png)

Can you give the hyper-parameters setting for the batch size=64?
