### ISSUE TITLE
Can't reproduce MSMT17 results

### ISSUE THREAD

**Issue by hu-zheng** [alibaba/cluster-contrast-reid#14]
Thanks for your work!
I reproduce the result of in dataset Market1501 and Duke, but I have some problem in MSMT17.
I trained MSMT17 using 4GPUs as follow 
`CUDA_VISIBLE_DEVICES=0,1,2,3 python examples/cluster_contrast_train_usl.py -b 256 -a resnet50 -d msmt17 --iters 400 --momentum 0.1 --eps 0.7 --num-instances 16
`
My best result of MSMT17 was about 20 which is lower than your result map=33.3 metioned in the paper. What's the problom?
Could you tell me how to adjust some specific hyper-parameters can improve the performance

**Comment by Git-Yxt** [comment]
I have the similiar problem with you。Differently, i use 1 GPU, and batchsize=64, my best result of MSMT17 is about 26%. Have you solved the problem?

**Comment by sudalvxin** [comment]
I use “CUDA_VISIBLE_DEVICES=2 python examples/cluster_contrast_train_usl.py -b 256 -a resnet50 -d market1501 --iters 200 --momentum 0.1 --eps 0.4 --num-instances 16” for Market1501, but the best results are：
Mean AP: 63.1%
CMC Scores:
  top-1          79.8%
  top-5          88.5%
  top-10         91.4%

**Comment by xmy0916** [comment]
have you solved the problem?

**Comment by hu-zheng** [comment]
No, i still haven't resolved.



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 5, 2021 12:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alibaba/cluster-contrast-reid] Can't reproduce MSMT17 results (#14)




 
have you solved the problem?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xmy0916** [comment]
I see dataset MSMT17 have two version. And i find the code here [link](https://github.com/alibaba/cluster-contrast-reid/blob/main/clustercontrast/datasets/msmt17.py#L40) it used bounding_box_train file. But in MSMT17_V1 there are only train and test directories. So did you change your MSMT17 dataset into Market1501 format? Maybe you used the different version of dataset MSMT17 compare to author, i think...

**Comment by xmy0916** [comment]
@hu-zheng 师兄好...看你头像眼熟，之前看了你在arxiv上的paper hhcl，我也是北邮的

**Comment by xmy0916** [comment]
@hu-zheng arxiv上的hhcl是不是您的文章呀，我也是北邮的^-^

**Comment by hu-zheng** [comment]
欢迎交流和学习🤝



---Original---
From: ***@***.***&gt;
Date: Fri, Nov 5, 2021 12:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alibaba/cluster-contrast-reid] Can't reproduce MSMT17 results (#14)




 
@hu-zheng 师兄好...看你头像眼熟，之前看了你在arxiv上的paper hhcl，我也是北邮的
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xmy0916** [comment]
@hu-zheng 方便加个微信吗我的vx：xmy_19980916😬

**Comment by wangguangyuan** [comment]
Hello, I have updated the code, please update the code to the latest
