### ISSUE TITLE
关于Memory Initialization的一点问题

### ISSUE THREAD

**Issue by xmy0916** [alibaba/cluster-contrast-reid#15]
感谢作者在USL上的工作，关于您的论文我有点小疑问，在3.2的Memory Initialization中我看您写的是在初始化Memory Initialization的时候随机选择聚类中的一个实例存储在Memory中，那么因为聚类会存在噪声，这个随机实例也可能是噪声样本，这样这个样本实际上不应该代表这个聚类，这样初始化不会有影响吗？我好像只在您论文中看到了您分析选择最难样本更新memory的时候如果是噪声样本的影响，没有看到对初始化时如果是噪声样本的分析，如果我有阅读不仔细还请见谅~希望作者抽空解答。
感谢！

**Comment by wangguangyuan** [comment]
你好，对于会引入噪声可以从这两个角度去考虑，一是我们知道聚类很难做到百分之百准确，一般会导致实际上是多个类别的样本聚类成一个类别，我们认为结果是有噪声的，但是我们统计了每类结果包含的实际类别样本数目发现聚类结果80%是属于同一类别，剩下的20%是噪声，如果我们选择随机初始化的话有80%的概率不会选择为噪声，如果我们选择均值初始化的话，因为我们也加入了噪声计算均值，可以认为是100%引入了噪声。二是我们的memory dictionary 是通过动量更新的，就算引入了噪声结果，进过几次的迭代噪声也会被更新掉。以上分析也解释了我们实验发现不同初始化多结果影响不大的原因。
![image](https://user-images.githubusercontent.com/5125004/128846542-4e920677-2f36-43d8-8754-626a772b2352.png)

**Comment by xmy0916** [comment]
感谢您的回复！

**Comment by SuperbTUM** [comment]
但是在11.19的文章版本里，这个初始化又变成了mean of cluster。。。

**Comment by xmy0916** [comment]
@SuperbTUM 平均的效果更好的
