### ISSUE TITLE
关于use hard的问题

### ISSUE THREAD

**Issue by xmy0916** [alibaba/cluster-contrast-reid#17]
作者您好！感谢您的工作 ~
我在market1501上测试代码效果确实如您论文所述，但是我在veri776上测试，使用ibn，参考run_code.sh里面veri上的命令训练得到的结果mAP为43.0较您论文43.6有点差距，然后我加上--use_hard参数得到的结果反而不如43.0了，请问加上这个参数还需要修改其他超参吗？您论文中的指标加上了--use_hard么？感谢您抽空回答。

**Comment by wangguangyuan** [comment]
你好感谢对我们工作的关注，use_hard训练不是特别稳定，如果不是追求特别高的精度，建议不用use_hard,这是我的微信具体细节可以加微信聊13051830011

**Comment by sudalvxin** [comment]
> 作者您好！感谢您的工作 ~
> 我在market1501上测试代码效果确实如您论文所述，但是我在veri776上测试，使用ibn，参考run_code.sh里面veri上的命令训练得到的结果mAP为43.0较您论文43.6有点差距，然后我加上--use_hard参数得到的结果反而不如43.0了，请问加上这个参数还需要修改其他超参吗？您论文中的指标加上了--use_hard么？感谢您抽空回答。

请问是直接跑的吗？我调用的：CUDA_VISIBLE_DEVICES=2 python examples/cluster_contrast_train_usl.py -b 256 -a resnet50 -d market1501 --iters 200 --momentum 0.1 --eps 0.4 --num-instances 16 得到的mAP只有63.31

**Comment by xmy0916** [comment]
@sudalvxin 你单卡跑的虽然batchsize一样大，但是卡数不一样，建议用四卡跑，单卡跑理论上学习率得除以4，但可能还是会有diff

**Comment by sudalvxin** [comment]
> @sudalvxin 你单卡跑的虽然batchsize一样大，但是卡数不一样，建议用四卡跑，单卡跑理论上学习率得除以4，但可能还是会有diff

好的，非常感谢！
