### ISSUE TITLE
PersonX 数据集上mAP只有36.0左右

### ISSUE THREAD

**Issue by jinx-USTC** [alibaba/cluster-contrast-reid#20]
你好，请问PersonX上的训练参数Command是怎么的，方便提供一下么，是不是哪里需要额外设置，我这边目前测的mAP很低只有36.0左右，跟文章中报的84.8相差甚远。

**Comment by wangguangyuan** [comment]
你好可以提供一下配置吗?

**Comment by wangguangyuan** [comment]
你好, 我把代码进行了更新,可以试试效果

**Comment by tengxiao14** [comment]
> 你好, 我把代码进行了更新,可以试试效果

您好，我想请教一个问题，你们最新上传的论文结果写的应该是resnet50加average pooling吧？为什么代码默认的参数是gem pooling，我把pooling type改成avg之后，在market1501上mAP只有80.9%，比论文里面的数值低了一点几个百分点，改成hard sampling结果更低，请问能不能提供下你们论文实验的指令吗？

**Comment by haichuntai** [comment]
> 

请问这个问题解决了么，是什么原因呢

**Comment by haichuntai** [comment]
> > 你好, 我把代码进行了更新,可以试试效果
> 
> 您好，我想请教一个问题，你们最新上传的论文结果写的应该是resnet50加average pooling吧？为什么代码默认的参数是gem pooling，我把pooling type改成avg之后，在market1501上mAP只有80.9%，比论文里面的数值低了一点几个百分点，改成hard sampling结果更低，请问能不能提供下你们论文实验的指令吗？

请问这个问题解决了么，是什么原因呢

**Comment by theziqi** [comment]
> > > 你好, 我把代码进行了更新,可以试试效果
> > 
> > 
> > 您好，我想请教一个问题，你们最新上传的论文结果写的应该是resnet50加average pooling吧？为什么代码默认的参数是gem pooling，我把pooling type改成avg之后，在market1501上mAP只有80.9%，比论文里面的数值低了一点几个百分点，改成hard sampling结果更低，请问能不能提供下你们论文实验的指令吗？
> 
> 请问这个问题解决了么，是什么原因呢

我也是这种情况，总是差一个点，请问现在有解决思路了吗

**Comment by diyifirstone** [comment]
personx_v1怎么有6个，具体使用哪个来训练？
