### ISSUE TITLE
Why the result cannot be reproduced?

### ISSUE THREAD

**Issue by tengxiao14** [alibaba/cluster-contrast-reid#23]
The result of the paper is produced with average pooling, but the default hyper-parameter of the code is gem pooling. When I replaced the hyper-parameter with average pooling, the mAP of resnet50 on market1501 is only 80.9%, which is lower than 82.1% in the paper. I would appreciate it if you could could provide me with the command to reproduce the result in the paper.

**Comment by wangguangyuan** [comment]
微信聊 13051830011

**Comment by theziqi** [comment]
I meet the same problem, the mAP of resnet50 on market1501 is 80.9% too. Could you tell me how to deal with it?
