### ISSUE TITLE
Can't reproduce the result of MTMC17 to 33.3 using avg pooling

### ISSUE THREAD

**Issue by haichuntai** [alibaba/cluster-contrast-reid#28]
The code use the gem as the polling layer and I only got 29.2 with the setting of cm. Is it normal?
More importantly, I can't get the same result when I use the avg pooling, which is about 20. 
Besides, I using the gem and cmhard also get a worse result.

**Comment by micmic123** [comment]
Hello, same issue here.
Did you reproduce the results of the paper for MSMT dataset?

**Comment by hongyan-an** [comment]
> Hello, same issue here. Did you reproduce the results of the paper for MSMT dataset?

yeah，i have same question.we can talk about it.please wechat

**Comment by hongyan-an** [comment]
> > Hello, same issue here. Did you reproduce the results of the paper for MSMT dataset?
> 
> yeah，i have same question.how many is the result in MSMT for you?
