### ISSUE TITLE
Why this paper is not accepted...

### ISSUE THREAD

**Issue by dyhBUPT** [alibaba/cluster-contrast-reid#30]
Hi, thanks for your excellent work and codes.

I like this work very much.
It has a clear and simple motivation, and superior performance.
So I'm a little confused about why this paper doesn't appear in some conference or journal.
Was it submitted to some conference but is rejected? If so, why???

I'm sorry if I offended you.

**Comment by Sunshine19980919** [comment]
This paper seems to have been included in ACCV2022
