### ISSUE TITLE
faiss:gpu  out of memory

### ISSUE THREAD

**Issue by CompliceU** [alibaba/cluster-contrast-reid#4]
Hello, due to the large amount of my data used, the faiss_gpu used in clustering always overflows. I don’t know how to deal with it, ask for guidance

**Comment by CompliceU** [comment]
@alibaba-oss

**Comment by Git-Yxt** [comment]
> Hello, due to the large amount of my data used, the faiss_gpu used in clustering always overflows. I don’t know how to deal with it, ask for guidance

hello,I got some problems with faiss-gpu , could you please tell me which version of faiss-gpu do you use?

**Comment by CompliceU** [comment]
@daizuozhuo

**Comment by daizuozhuo** [comment]
In each epoch, you can only sample a fraction of data for training. This requires you to modify code.
