### ISSUE TITLE
Parameter configuration for Duke and MSMT17 dataset, as well as memory initialization

### ISSUE THREAD

**Issue by Terminator8758** [alibaba/cluster-contrast-reid#5]
Hi, thanks for releasing the implementation code of your method. I have two questions about the code:

1. From the other issues, i can see that the hyper-parameter configuration is give for Market-1501. Following the configuration, i'm able to obtain the same result as your paper (on Market-1501 using Resnet-50 and average pooling: rank1=92.8%, mAP=83.1%). However, when i run the code on DukeMTMC-reID and MSMT17 following the guidance of the ReadMe.md, the result is low and cannot match the performance of the paper. So can you provide the specific parameter values (such as eps), so that the performance on other two datasets can be achieved?

2. The paper introduces random sample initialization and hard sample update for the memory bank. But from Line 175 in examples/cluster_contrast_train_usl.py, it seems that mean feature is adopted as initialization, instead of random feature. So i want to know if the paper full model is achieved using mean feature or random feature initialization. Thanks!

**Comment by daizuozhuo** [comment]
Please check the run_code.sh for other dataset training script. The memory initialization method does not affect the final performance.
