### ISSUE TITLE
duke on 1 GTX 2080ti,the mAP can not reach 72.8%

### ISSUE THREAD

**Issue by Git-Yxt** [alibaba/cluster-contrast-reid#6]
I run the duke dataset  on 1 GTX2080ti, then  I set the parameters as below:
batch_size=64
num_instances=4
iters=200
pooling-type=gem
momentum=0.1
use-hard
lr=0.00035
the other parameters are same as before, finally I got mAP 70.3%, (< mAP 72.8% in paper).
Is it any chance to reach 72.8% when I only use 1 GTX 2080ti?

**Comment by daizuozhuo** [comment]
I didn't try one card. The paper result is achieved by batch size 256, so may be increase batch size would be helpful.
