### ISSUE TITLE
实验多次复现结果不同的问题

### ISSUE THREAD

**Issue by hu-zheng** [alibaba/cluster-contrast-reid#7]
作者，您好！
请问一下，我使用相同的配置和设备，在固定随机种子的情况下，为什么自己跑出来两次的结果还会有差异，而且结果有时差别还很大（mAP能有1.5个点的浮动），请问这个是正常的吗？有没有办法可以固定住。

**Comment by tangsipeng** [comment]
CUDA_VISIBLE_DEVICES=0,1 python examples/cluster_contrast_train_usl.py -b 256 -a resnet50 -d market1501 --iters 200 --momentum 0.1 --eps 0.4 --num-instances 16

Mean AP: 79.6%
CMC Scores:
  top-1          90.3%
  top-5          95.5%
  top-10         97.0%

**Comment by keenJMS** [comment]
So, the final result is to pick the best one?
