### ISSUE TITLE
why the cluster_loader uses test data augmentation mode instead of training mode?

### ISSUE THREAD

**Issue by knaffe** [alibaba/cluster-contrast-reid#8]
Thank you for your great contribution !
I check the code and notice: 
`cluster_loader = get_test_loader(dataset, args.height, args.width,
                                             args.batch_size, args.workers, testset=sorted(dataset.train))`
why don't you use the training mode augmentation with this train set for cluster?

**Comment by daizuozhuo** [comment]
Running clustering algorithm on un-augmented images produces higher quality pseudo labels. Experiments show that using test loader performs better.
